### ISSUE TITLE
Default to SHA512

### ISSUE THREAD

**Issue by chillu** [elliot-sawyer/totp-authenticator#14]
The lib allows configuring it, and according to this [stackoverflow thread](https://security.stackexchange.com/questions/45904/is-hmac-sha256-and-hmac-sha512-able-to-act-as-drop-in-replacement-for-hmac-sha1#45907) it should just work. A stronger hashing algo would comply with common security standards such as NZISM.

But looking at the [Google Authenticator](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#algorithm) spec for the key uri format, it marks the `algorithm` parameter as ignored. There's also [issues on other TOTP libs](https://github.com/pquerna/otp/issues/26) where clients run into trouble. [1Password](https://discussions.agilebits.com/discussion/53425/totp-sha512-incorrectly-generated) seems to handle it fine.

Might be in the too hard basket?

/cc @Firesphere

**Comment by elliot-sawyer** [comment]
See Issue #7. Authy and Google Authenticator don't support SHA512. I have raised a PR to configure it: https://github.com/elliot-sawyer/totp-authenticator/pull/10

**Comment by chillu** [comment]
lol I raised an issue with the exact same title ... classic. OK closing this off as well, good to see it's been considered.
