### ISSUE TITLE
Add Travis and Scrutinizer CI

### ISSUE THREAD

**Issue by robbieaverill** [elliot-sawyer/totp-authenticator#19]
Hey @elliot-sawyer 

These two tasks need to be done by a repository administrator. Would you mind adding them both? I can take care of the config for them, and #17 is logged to add some tests =)

**Comment by elliot-sawyer** [comment]
@robbieaverill I think this is done, can you confirm?

**Comment by robbieaverill** [comment]
Yep, just needs config (I'll do it today)

**Comment by robbieaverill** [comment]
PR is at #23
